configName: sam_a5d2_xult_freertos_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\MCU_MPU\SAMA5\H3_MPU
processor: ATSAMA5D27
projectName: spi_self_loopback_multi_client_freertos_sam_a5d2_xult_freertos
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;micrium_ucos3;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.2.30\atdf\ATSAMA5D27.atdf
  MERGE_STRATEGY: USER_ALL
