package:
  format-version: "1.0.0"
  name: "core_apps_sam_a5d2"
  version: "v3.4.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
<<<<<<< HEAD
      version: "v3.17.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "core"
      type: "package"
      version: "v3.13.0"
=======
      version: "3.18.3"
    - name: "dev_packs"
      type: "package"
      version: "3.18.1"
    - name: "core"
      type: "package"
      version: "3.13.3"
>>>>>>> ed4136be ([Docs] Add SDL Documentation for core apps of sam_a5d2_curiosity)
