package:
  format-version: "1.0.0"
  name: "core_apps_sam_a5d2"
  version: "v3.4.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.18.3"
    - name: "core"
      type: "package"
      version: "3.13.3"
    - name: "bsp"
      type: "package"
      version: "3.18.0"
