format_version: v1.0
type: UniqueComponent
attributes: {id: drv_at25df}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DRV_AT25DF_CHIP_SELECT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '17'}
  - type: String
    attributes: {id: DRV_AT25DF_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_at25df, value: SPI0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_at25df_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: spi0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI0_SPI}
- type: ElementPosition
  attributes: {x: '378', y: '139', id: drv_at25df}
