format_version: v1.0
type: UniqueComponent
attributes: {id: drv_mx25l}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_MX25L_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_mx25l, value: QSPI0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_mx25l_SQI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: qspi0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: QSPI0_SQI}
- type: ElementPosition
  attributes: {x: '406', y: '76', id: drv_mx25l}
