configName: sama5d29_curiosity_freertos
folderName: sama5d29_curiosity_freertos
format_version: v1.0
frameworkPath: C:\microchip\harmony\h3
processor: ATSAMA5D29
projectName: sama5d29_curiosity_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMA5D2_DFP\1.10.213
