format_version: v1.0
type: UniqueComponent
attributes: {id: qspi0}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '0'}
  - type: KeyValueSet
    attributes: {id: QSPI_SMM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '0'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: QSPI0_SPI}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: QSPI0_SQI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_mx25l}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_mx25l_SQI_dependency}
- type: ElementPosition
  attributes: {x: '328', y: '276', id: qspi0}
